services:
  rinha-api-1:
    build:
      dockerfile: Dockerfile.api
    networks:
      - payment-processor
      - app-network
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - health-check
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "30MB"

  rinha-api-2:
    build:
      dockerfile: Dockerfile.api
    networks:
      - payment-processor
      - app-network
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - health-check
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "30MB"

  nginx:
    image: nginx:latest
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rinha-api-1
      - rinha-api-2
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

  redis:
    image: redis/redis-stack-server:latest
    volumes:
      - ./redis-startup.sh:/usr/local/bin/entrypoint.sh
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    networks:
      - app-network
    deploy:
        resources:
          limits:
            cpus: "0.3"
            memory: "250MB"

  health-check:
    build:
      dockerfile: Dockerfile.healthcheck
    networks:
      - payment-processor
      - app-network
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

networks:
  app-network:
    driver: bridge
  payment-processor:
    external: true
