services:
  api-1:
    build:
      dockerfile: Dockerfile.api
    networks:
      - payment-processor
      - app-network
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - health-check
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "75MB"

  api-2:
    build:
      dockerfile: Dockerfile.api
    networks:
      - payment-processor
      - app-network
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - health-check
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "75MB"

  worker:
    build:
      dockerfile: Dockerfile.worker
    networks:
      - payment-processor
      - app-network
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - health-check
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "75MB"

  nginx:
    image: nginx:latest
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  redis:
    image: redis:alpine
    command: redis-server --save ""
    networks:
      - app-network
    deploy:
        resources:
          limits:
            cpus: "0.1"
            memory: "50MB"

  health-check:
    build:
      dockerfile: Dockerfile.healthcheck
    networks:
      - payment-processor
      - app-network
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "25MB"

networks:
  app-network:
    driver: bridge
  payment-processor:
    external: true
